### PR TITLE
Add RISC-V support

### PR DESCRIPTION
**Pull request by Amanieu**
The vendored capstone is updated to include https://github.com/aquynh/capstone/pull/1682.

### CODE REVIEW

**Comment by Amanieu** [comment]
CI failure seems to be unrelated, the same error happens on master.

**Comment by tmfink** [comment]
Thanks for the PR, this looks really great!

My only request is that you add some unit tests, which will increase confidence (especially when we make subsequent upgrades to the bundled capstone). I suggest convert several of the instructions from `capstone-sys/capstone/tests/test_riscv.c`.

As an example, take a look at `capstone-rs/src/test.rs` tests `test_arch_mips()`/`test_arch_mips_detail()`.

**Comment by Amanieu** [comment]
I did add tests: https://github.com/capstone-rust/capstone-rs/pull/100/files#diff-a1c12c7efdc33c34fd3c1e0d29eec806c2444907eb898f64356208960fbae58f

**Comment by tmfink** [comment]
> I did add tests: https://github.com/capstone-rust/capstone-rs/pull/100/files#diff-a1c12c7efdc33c34fd3c1e0d29eec806c2444907eb898f64356208960fbae58f

Sorry--don't know how I missed that. Thanks for the contribution!

**Comment by Amanieu** [comment]
Could you publish a new version with this change?

**Comment by Amanieu** [comment]
Ping for publishing a new release.

**Comment by tmfink** [comment]
I published version `0.9.0`.

**Pull request merged**
